services:
  qbittorrent-nox:
    # for debugging
    #cap_add:
     #- SYS_PTRACE
    container_name: qbittorrent-nox
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - QBT_LEGAL_NOTICE=${QBT_LEGAL_NOTICE}
      - QBT_WEBUI_PORT=${QBT_WEBUI_PORT}
      - TZ=${TZ}
      #- UMASK=022
    image: qbittorrentofficial/qbittorrent-nox:5.2.3-1
    ports:
      # for bittorrent traffic
      - ${QBT_TORRENT_PORT}:${QBT_TORRENT_PORT}/tcp
      - ${QBT_TORRENT_PORT}:${QBT_TORRENT_PORT}/udp
      # for WebUI
      - ${QBT_WEBUI_PORT}:${QBT_WEBUI_PORT}/tcp
    #read_only: true
    # Upstream recommends 30m to allow qBittorrent to shut down cleanly.
    stop_grace_period: 30m
    tmpfs:
      - /tmp
    tty: true
    volumes:
      - ${QBT_CONFIG_PATH}:/config
      - ${QBT_DOWNLOADS_PATH}:/downloads
  qbittorrent-log:
    image: busybox:1.38.0
    container_name: qbittorrent-log
    restart: unless-stopped
    depends_on:
      - qbittorrent-nox
    volumes:
      - ${QBT_CONFIG_PATH}:/config:ro
    command: >
      sh -c "tail -n 100 -F /config/qBittorrent/data/logs/qbittorrent.log"
