services:
  grocy:
    image: ghcr.io/linuxserver/grocy:v4.7.1-ls341
    container_name: grocy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${GROCY_CONFIG_DIR}:/config
    ports:
      - "${GROCY_BIND}:${GROCY_PORT}:80"
    restart: unless-stopped
