services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    user: "${PUID}:${PGID}"
    network_mode: bridge
    ports:
      - "${JELLYFIN_BIND}:${JELLYFIN_PORT}:8096"
    volumes:
      - "${MEDIA_DIR}:/media"
      - ./cache:/cache/
      - ./config:/config
    restart: unless-stopped
    environment:
      - TZ=${TZ}
